# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Título do Livro
lang: pt-br
email: math.raduan@gmail.com
description: "Esse é um livro interativo online que foi desenvolvido pelos alunos Jonas Custódio e Matheus Raduan
para a disciplina de Ficção Interativa do curso de Jogos Digitais da Fatec Americana. Feito com muito <amor3, café ☕ e <código/>."
baseurl: /book-interactive-fiction # the subpath of your site, e.g. /blog
url: "/book-interactive-fiction" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: math_raduan
github_username:  MRRaduan

author_j: Jonas Custódio
author_m: Matheus Raduan
book_title: Título do livro
team: Dream Team

# Build settings
markdown: kramdown
#permalink: /:categories/:year/:month/:day/:title
#permalink: /:year/:month/:day/:title/:categories/:year/:month/:day
permalink: /:title
theme: minima
plugins:
  - jekyll-feed

